package com.neu.ms.mbg.model;

import java.util.Date;

public class MsAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.id
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.nick_name
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.username
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.password
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.create_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.end_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.status
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.avatar_address
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    private String avatarAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.id
     *
     * @return the value of ms_admin.id
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.id
     *
     * @param id the value for ms_admin.id
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.nick_name
     *
     * @return the value of ms_admin.nick_name
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.nick_name
     *
     * @param nickName the value for ms_admin.nick_name
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.username
     *
     * @return the value of ms_admin.username
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.username
     *
     * @param username the value for ms_admin.username
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.password
     *
     * @return the value of ms_admin.password
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.password
     *
     * @param password the value for ms_admin.password
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.create_time
     *
     * @return the value of ms_admin.create_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.create_time
     *
     * @param createTime the value for ms_admin.create_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.end_time
     *
     * @return the value of ms_admin.end_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.end_time
     *
     * @param endTime the value for ms_admin.end_time
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.status
     *
     * @return the value of ms_admin.status
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.status
     *
     * @param status the value for ms_admin.status
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.avatar_address
     *
     * @return the value of ms_admin.avatar_address
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public String getAvatarAddress() {
        return avatarAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.avatar_address
     *
     * @param avatarAddress the value for ms_admin.avatar_address
     *
     * @mbg.generated Mon Jun 14 15:07:29 CST 2021
     */
    public void setAvatarAddress(String avatarAddress) {
        this.avatarAddress = avatarAddress;
    }
}