package com.neu.ms.mbg.model;

public class MsAdminAndRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin_and_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin_and_role.admin_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin_and_role.role_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin_and_role.id
     *
     * @return the value of ms_admin_and_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin_and_role.id
     *
     * @param id the value for ms_admin_and_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin_and_role.admin_id
     *
     * @return the value of ms_admin_and_role.admin_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin_and_role.admin_id
     *
     * @param adminId the value for ms_admin_and_role.admin_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin_and_role.role_id
     *
     * @return the value of ms_admin_and_role.role_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin_and_role.role_id
     *
     * @param roleId the value for ms_admin_and_role.role_id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}