package com.neu.ms.mbg.model;

public class MsAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.id
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.username
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.password
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_admin.level
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.id
     *
     * @return the value of ms_admin.id
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.id
     *
     * @param id the value for ms_admin.id
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.username
     *
     * @return the value of ms_admin.username
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.username
     *
     * @param username the value for ms_admin.username
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.password
     *
     * @return the value of ms_admin.password
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.password
     *
     * @param password the value for ms_admin.password
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_admin.level
     *
     * @return the value of ms_admin.level
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_admin.level
     *
     * @param level the value for ms_admin.level
     *
     * @mbggenerated Tue Jan 26 20:25:55 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}