package com.neu.ms.mbg.model;

public class MsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.role_name
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.id
     *
     * @return the value of ms_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.id
     *
     * @param id the value for ms_role.id
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.role_name
     *
     * @return the value of ms_role.role_name
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.role_name
     *
     * @param roleName the value for ms_role.role_name
     *
     * @mbg.generated Sat Feb 06 16:18:31 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}