spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

server:
  port: 8088